type AppRole {
    id: Int!
    name: String!
    description: String
    permissions: [AppPermission!]!
    createdAt: String!
    updatedAt: String!
}

input CreateAppRoleInput {
    name: String!
    description: String
    permissionIds: [Int!]
}

input UpdateAppRoleInput {
    name: String
    description: String
    permissionIds: [Int!]
}

type Query {
    roles: [AppRole!]!
    role(id: Int!): AppRole!
}

type Mutation {
    createAppRole(input: CreateAppRoleInput!): AppRole!
    updateAppRole(id: Int!, input: UpdateAppRoleInput!): AppRole!
    deleteAppRole(id: Int!): Boolean!
}
